// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(r_shell_macosFFI)
import r_shell_macosFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_r_shell_macos_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_r_shell_macos_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * Parameters for creating an SSH connection.
 * Maps to a uniffi `dictionary` in Swift; generated bindings produce
 * a native Swift struct that callers construct inline.
 */
public struct FfiConnectConfig {
    public var host: String
    public var port: UInt16
    public var username: String
    /**
     * Password for password-based auth. May be `None` when using key-based auth.
     */
    public var password: String?
    /**
     * Filesystem path to a private key for key-based auth. May be `None`
     * when using password auth.
     */
    public var keyPath: String?
    /**
     * Optional passphrase to decrypt the private key.
     */
    public var passphrase: String?
    /**
     * Optional unique suffix that lets the same `(user, host, port)` triple
     * be opened more than once (e.g., one terminal tab per session). When
     * `Some("abc")`, the connection is keyed as `"user@host:port#abc"` in
     * `pty_sessions`. When `None`, the bare key is used (suitable for the
     * simple "single connection per host" case).
     */
    public var sessionId: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(host: String, port: UInt16, username: String, 
        /**
         * Password for password-based auth. May be `None` when using key-based auth.
         */password: String?, 
        /**
         * Filesystem path to a private key for key-based auth. May be `None`
         * when using password auth.
         */keyPath: String?, 
        /**
         * Optional passphrase to decrypt the private key.
         */passphrase: String?, 
        /**
         * Optional unique suffix that lets the same `(user, host, port)` triple
         * be opened more than once (e.g., one terminal tab per session). When
         * `Some("abc")`, the connection is keyed as `"user@host:port#abc"` in
         * `pty_sessions`. When `None`, the bare key is used (suitable for the
         * simple "single connection per host" case).
         */sessionId: String?) {
        self.host = host
        self.port = port
        self.username = username
        self.password = password
        self.keyPath = keyPath
        self.passphrase = passphrase
        self.sessionId = sessionId
    }
}



extension FfiConnectConfig: Equatable, Hashable {
    public static func ==(lhs: FfiConnectConfig, rhs: FfiConnectConfig) -> Bool {
        if lhs.host != rhs.host {
            return false
        }
        if lhs.port != rhs.port {
            return false
        }
        if lhs.username != rhs.username {
            return false
        }
        if lhs.password != rhs.password {
            return false
        }
        if lhs.keyPath != rhs.keyPath {
            return false
        }
        if lhs.passphrase != rhs.passphrase {
            return false
        }
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(host)
        hasher.combine(port)
        hasher.combine(username)
        hasher.combine(password)
        hasher.combine(keyPath)
        hasher.combine(passphrase)
        hasher.combine(sessionId)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiConnectConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiConnectConfig {
        return
            try FfiConnectConfig(
                host: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf), 
                username: FfiConverterString.read(from: &buf), 
                password: FfiConverterOptionString.read(from: &buf), 
                keyPath: FfiConverterOptionString.read(from: &buf), 
                passphrase: FfiConverterOptionString.read(from: &buf), 
                sessionId: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiConnectConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.host, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
        FfiConverterString.write(value.username, into: &buf)
        FfiConverterOptionString.write(value.password, into: &buf)
        FfiConverterOptionString.write(value.keyPath, into: &buf)
        FfiConverterOptionString.write(value.passphrase, into: &buf)
        FfiConverterOptionString.write(value.sessionId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiConnectConfig_lift(_ buf: RustBuffer) throws -> FfiConnectConfig {
    return try FfiConverterTypeFfiConnectConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiConnectConfig_lower(_ value: FfiConnectConfig) -> RustBuffer {
    return FfiConverterTypeFfiConnectConfig.lower(value)
}


/**
 * An event emitted by the Rust core and delivered to the Swift layer via
 * the registered `FfiEventCallback`.
 *
 * `ty` identifies the event kind: `"pty_output"`, `"connection_status"`,
 * `"transfer_progress"`, or `"action_complete"`.
 *
 * `connection_id` is the connection this event relates to.
 *
 * `payload` is a JSON-encoded string with the event-specific data.
 */
public struct FfiEvent {
    public var ty: String
    public var connectionId: String
    public var payload: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ty: String, connectionId: String, payload: String) {
        self.ty = ty
        self.connectionId = connectionId
        self.payload = payload
    }
}



extension FfiEvent: Equatable, Hashable {
    public static func ==(lhs: FfiEvent, rhs: FfiEvent) -> Bool {
        if lhs.ty != rhs.ty {
            return false
        }
        if lhs.connectionId != rhs.connectionId {
            return false
        }
        if lhs.payload != rhs.payload {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(ty)
        hasher.combine(connectionId)
        hasher.combine(payload)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiEvent: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiEvent {
        return
            try FfiEvent(
                ty: FfiConverterString.read(from: &buf), 
                connectionId: FfiConverterString.read(from: &buf), 
                payload: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiEvent, into buf: inout [UInt8]) {
        FfiConverterString.write(value.ty, into: &buf)
        FfiConverterString.write(value.connectionId, into: &buf)
        FfiConverterString.write(value.payload, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEvent_lift(_ buf: RustBuffer) throws -> FfiEvent {
    return try FfiConverterTypeFfiEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEvent_lower(_ value: FfiEvent) -> RustBuffer {
    return FfiConverterTypeFfiEvent.lower(value)
}


public struct FfiFileEntry {
    public var name: String
    public var size: UInt64
    /**
     * Pre-formatted timestamp string from r-shell-core. `None` when
     * the SFTP server doesn't supply mtime.
     */
    public var modified: String?
    /**
     * Pre-formatted POSIX permission string (e.g. `rwxr-xr-x`).
     */
    public var permissions: String?
    public var kind: FfiFileKind

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, size: UInt64, 
        /**
         * Pre-formatted timestamp string from r-shell-core. `None` when
         * the SFTP server doesn't supply mtime.
         */modified: String?, 
        /**
         * Pre-formatted POSIX permission string (e.g. `rwxr-xr-x`).
         */permissions: String?, kind: FfiFileKind) {
        self.name = name
        self.size = size
        self.modified = modified
        self.permissions = permissions
        self.kind = kind
    }
}



extension FfiFileEntry: Equatable, Hashable {
    public static func ==(lhs: FfiFileEntry, rhs: FfiFileEntry) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.size != rhs.size {
            return false
        }
        if lhs.modified != rhs.modified {
            return false
        }
        if lhs.permissions != rhs.permissions {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(size)
        hasher.combine(modified)
        hasher.combine(permissions)
        hasher.combine(kind)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiFileEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiFileEntry {
        return
            try FfiFileEntry(
                name: FfiConverterString.read(from: &buf), 
                size: FfiConverterUInt64.read(from: &buf), 
                modified: FfiConverterOptionString.read(from: &buf), 
                permissions: FfiConverterOptionString.read(from: &buf), 
                kind: FfiConverterTypeFfiFileKind.read(from: &buf)
        )
    }

    public static func write(_ value: FfiFileEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt64.write(value.size, into: &buf)
        FfiConverterOptionString.write(value.modified, into: &buf)
        FfiConverterOptionString.write(value.permissions, into: &buf)
        FfiConverterTypeFfiFileKind.write(value.kind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFileEntry_lift(_ buf: RustBuffer) throws -> FfiFileEntry {
    return try FfiConverterTypeFfiFileEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFileEntry_lower(_ value: FfiFileEntry) -> RustBuffer {
    return FfiConverterTypeFfiFileEntry.lower(value)
}


/**
 * Universal result struct for FFI operations.
 *
 * `success` indicates whether the operation completed. When `success` is
 * `false`, `error` contains a human-readable description of what went wrong.
 * When `success` is `true`, `value` may carry extra payload (e.g. a PTY
 * generation counter as a JSON string).
 */
public struct FfiResult {
    public var success: Bool
    public var error: String?
    /**
     * JSON-encoded extra payload (e.g. `{"generation": 3}` for PTY start)
     */
    public var value: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(success: Bool, error: String?, 
        /**
         * JSON-encoded extra payload (e.g. `{"generation": 3}` for PTY start)
         */value: String?) {
        self.success = success
        self.error = error
        self.value = value
    }
}



extension FfiResult: Equatable, Hashable {
    public static func ==(lhs: FfiResult, rhs: FfiResult) -> Bool {
        if lhs.success != rhs.success {
            return false
        }
        if lhs.error != rhs.error {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(success)
        hasher.combine(error)
        hasher.combine(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiResult {
        return
            try FfiResult(
                success: FfiConverterBool.read(from: &buf), 
                error: FfiConverterOptionString.read(from: &buf), 
                value: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiResult, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.success, into: &buf)
        FfiConverterOptionString.write(value.error, into: &buf)
        FfiConverterOptionString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiResult_lift(_ buf: RustBuffer) throws -> FfiResult {
    return try FfiConverterTypeFfiResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiResult_lower(_ value: FfiResult) -> RustBuffer {
    return FfiConverterTypeFfiResult.lower(value)
}


/**
 * Typed connect-time failures so the Swift side can pattern-match instead
 * of substring-checking the error string. Variants are classified from
 * the underlying `anyhow::Error` produced by `r-shell-core` based on
 * well-known message phrases — uniffi 0.28 doesn't propagate Rust types
 * through `anyhow`, so this is the natural place for the classification.
 */
public enum ConnectError {

    
    
    /**
     * Either no auth method was provided, or the request was missing a
     * required field. The user can't recover by retrying — they need to
     * fix the profile.
     */
    case ConfigInvalid(detail: String
    )
    /**
     * SSH key is encrypted and either no passphrase was supplied or the
     * supplied one was wrong. The Swift side typically prompts and
     * retries.
     */
    case PassphraseRequired(detail: String
    )
    /**
     * Server rejected the credential — wrong password, key not in
     * `authorized_keys`, etc. Distinct from `PassphraseRequired` because
     * the recovery flow differs (re-prompt password vs unlock key).
     */
    case AuthFailed(detail: String
    )
    /**
     * The stored host fingerprint doesn't match the offered one. Caller
     * must surface the mismatch so the user can decide whether to
     * re-trust the host (and removes the old TOFU entry).
     */
    case HostKeyMismatch(detail: String
    )
    /**
     * TCP-level failure: timeout, refused, reset, allow-list block.
     */
    case Network(detail: String
    )
    /**
     * Anything else — unknown error string from r-shell-core. Swift falls
     * through to a generic alert.
     */
    case Other(detail: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectError: FfiConverterRustBuffer {
    typealias SwiftType = ConnectError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ConfigInvalid(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 2: return .PassphraseRequired(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 3: return .AuthFailed(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 4: return .HostKeyMismatch(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Network(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 6: return .Other(
            detail: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ConnectError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ConfigInvalid(detail):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .PassphraseRequired(detail):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .AuthFailed(detail):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .HostKeyMismatch(detail):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .Network(detail):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .Other(detail):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


extension ConnectError: Equatable, Hashable {}

extension ConnectError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiCredentialKind {
    
    case sshPassword
    case sshKeyPassphrase
    case sftpPassword
    case sftpKeyPassphrase
    case ftpPassword
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCredentialKind: FfiConverterRustBuffer {
    typealias SwiftType = FfiCredentialKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCredentialKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .sshPassword
        
        case 2: return .sshKeyPassphrase
        
        case 3: return .sftpPassword
        
        case 4: return .sftpKeyPassphrase
        
        case 5: return .ftpPassword
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiCredentialKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .sshPassword:
            writeInt(&buf, Int32(1))
        
        
        case .sshKeyPassphrase:
            writeInt(&buf, Int32(2))
        
        
        case .sftpPassword:
            writeInt(&buf, Int32(3))
        
        
        case .sftpKeyPassphrase:
            writeInt(&buf, Int32(4))
        
        
        case .ftpPassword:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCredentialKind_lift(_ buf: RustBuffer) throws -> FfiCredentialKind {
    return try FfiConverterTypeFfiCredentialKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCredentialKind_lower(_ value: FfiCredentialKind) -> RustBuffer {
    return FfiConverterTypeFfiCredentialKind.lower(value)
}



extension FfiCredentialKind: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiFileKind {
    
    case file
    case directory
    case symlink
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiFileKind: FfiConverterRustBuffer {
    typealias SwiftType = FfiFileKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiFileKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .file
        
        case 2: return .directory
        
        case 3: return .symlink
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiFileKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .file:
            writeInt(&buf, Int32(1))
        
        
        case .directory:
            writeInt(&buf, Int32(2))
        
        
        case .symlink:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFileKind_lift(_ buf: RustBuffer) throws -> FfiFileKind {
    return try FfiConverterTypeFfiFileKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFileKind_lower(_ value: FfiFileKind) -> RustBuffer {
    return FfiConverterTypeFfiFileKind.lower(value)
}



extension FfiFileKind: Equatable, Hashable {}




public enum SftpError {

    
    
    case NotConnected(connectionId: String
    )
    /**
     * User-initiated cancellation via `rshell_sftp_cancel`. Distinct
     * from `Other` so the UI can mark the transfer cancelled rather
     * than failed and skip the error toast.
     */
    case Cancelled
    case Other(detail: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSftpError: FfiConverterRustBuffer {
    typealias SwiftType = SftpError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SftpError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotConnected(
            connectionId: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Cancelled
        case 3: return .Other(
            detail: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SftpError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .NotConnected(connectionId):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(connectionId, into: &buf)
            
        
        case .Cancelled:
            writeInt(&buf, Int32(2))
        
        
        case let .Other(detail):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


extension SftpError: Equatable, Hashable {}

extension SftpError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




/**
 * Callback trait that the Swift layer implements to receive asynchronous
 * events from the Rust core. Registered once via `rshell_set_event_callback`.
 *
 * `FfiEventCallback` is `Send + Sync` so it can be invoked from any Tokio
 * task spawned by the bridge.
 */
public protocol FfiEventCallback : AnyObject {
    
    func onEvent(event: FfiEvent) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFfiEventCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceFfiEventCallback = UniffiVTableCallbackInterfaceFfiEventCallback(
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     event: try FfiConverterTypeFfiEvent.lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceFfiEventCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface FfiEventCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitFfiEventCallback() {
    uniffi_r_shell_macos_fn_init_callback_vtable_ffieventcallback(&UniffiCallbackInterfaceFfiEventCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceFfiEventCallback {
    fileprivate static var handleMap = UniffiHandleMap<FfiEventCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceFfiEventCallback : FfiConverter {
    typealias SwiftType = FfiEventCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiFileEntry: FfiConverterRustBuffer {
    typealias SwiftType = [FfiFileEntry]

    public static func write(_ value: [FfiFileEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiFileEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiFileEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiFileEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiFileEntry.read(from: &buf))
        }
        return seq
    }
}
/**
 * Establish an SSH connection. Returns the canonical connection id
 * (`"user@host:port"` or `"user@host:port#sessionId"`) on success;
 * throws a typed `ConnectError` on failure.
 */
public func rshellConnect(config: FfiConnectConfig)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeConnectError.lift) {
    uniffi_r_shell_macos_fn_func_rshell_connect(
        FfiConverterTypeFfiConnectConfig.lower(config),$0
    )
})
}
/**
 * Disconnect an SSH connection and tear down any associated PTY session.
 */
public func rshellDisconnect(connectionId: String) -> FfiResult {
    return try!  FfiConverterTypeFfiResult.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_disconnect(
        FfiConverterString.lower(connectionId),$0
    )
})
}
/**
 * Execute a remote command on an SSH connection and return the output.
 * Blocks until the command completes or fails.
 */
public func rshellExecuteCommand(connectionId: String, command: String) -> FfiResult {
    return try!  FfiConverterTypeFfiResult.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_execute_command(
        FfiConverterString.lower(connectionId),
        FfiConverterString.lower(command),$0
    )
})
}
/**
 * Forget a stored host-key entry. Called from the Swift "Trust new key"
 * flow after a `HostKeyMismatch` so the next connect TOFU-trusts the
 * new fingerprint. Returns `success: true, value: "true"` if an entry
 * was removed, `success: true, value: "false"` if there was nothing
 * to remove, or `success: false, error: ...` on disk I/O failure.
 */
public func rshellForgetHostKey(host: String, port: UInt16) -> FfiResult {
    return try!  FfiConverterTypeFfiResult.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_forget_host_key(
        FfiConverterString.lower(host),
        FfiConverterUInt16.lower(port),$0
    )
})
}
/**
 * Initialise the macOS bridge. Must be called once before any other
 * `rshell_*` function. Creates the Tokio runtime and connection manager.
 * Safe to call multiple times — subsequent calls are no-ops.
 */
public func rshellInit() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_init($0
    )
})
}
public func rshellKeychainDelete(kind: FfiCredentialKind, account: String) -> FfiResult {
    return try!  FfiConverterTypeFfiResult.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_keychain_delete(
        FfiConverterTypeFfiCredentialKind.lower(kind),
        FfiConverterString.lower(account),$0
    )
})
}
public func rshellKeychainIsSupported() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_keychain_is_supported($0
    )
})
}
public func rshellKeychainList(kind: FfiCredentialKind) -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_keychain_list(
        FfiConverterTypeFfiCredentialKind.lower(kind),$0
    )
})
}
public func rshellKeychainLoad(kind: FfiCredentialKind, account: String) -> FfiResult {
    return try!  FfiConverterTypeFfiResult.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_keychain_load(
        FfiConverterTypeFfiCredentialKind.lower(kind),
        FfiConverterString.lower(account),$0
    )
})
}
public func rshellKeychainSave(kind: FfiCredentialKind, account: String, secret: String) -> FfiResult {
    return try!  FfiConverterTypeFfiResult.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_keychain_save(
        FfiConverterTypeFfiCredentialKind.lower(kind),
        FfiConverterString.lower(account),
        FfiConverterString.lower(secret),$0
    )
})
}
/**
 * Close a PTY session. The `expected_generation` is the generation counter
 * returned by `rshell_pty_start`; if it doesn't match the current session,
 * the close is ignored (prevents stale-close races from component remounts).
 */
public func rshellPtyClose(connectionId: String, expectedGeneration: UInt64) -> FfiResult {
    return try!  FfiConverterTypeFfiResult.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_pty_close(
        FfiConverterString.lower(connectionId),
        FfiConverterUInt64.lower(expectedGeneration),$0
    )
})
}
/**
 * Resize a running PTY session's terminal dimensions.
 */
public func rshellPtyResize(connectionId: String, cols: UInt32, rows: UInt32) -> FfiResult {
    return try!  FfiConverterTypeFfiResult.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_pty_resize(
        FfiConverterString.lower(connectionId),
        FfiConverterUInt32.lower(cols),
        FfiConverterUInt32.lower(rows),$0
    )
})
}
/**
 * Start an interactive PTY session on an already-connected SSH connection.
 * Returns the generation counter in `value` (as a JSON string) so the
 * frontend can pass it back in `rshell_pty_close` to prevent stale closes.
 *
 * Spawns a background task that drains the PTY's `output_rx` channel and
 * publishes each chunk as a `CoreEvent::PtyOutput` on the event bus, so the
 * Swift event callback receives terminal output. The macOS app is the only
 * consumer of `output_rx` (Tauri uses `read_pty_burst` in its own process),
 * so there is no contention.
 */
public func rshellPtyStart(connectionId: String, cols: UInt32, rows: UInt32) -> FfiResult {
    return try!  FfiConverterTypeFfiResult.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_pty_start(
        FfiConverterString.lower(connectionId),
        FfiConverterUInt32.lower(cols),
        FfiConverterUInt32.lower(rows),$0
    )
})
}
/**
 * Write data (user input) to a running PTY session.
 */
public func rshellPtyWrite(connectionId: String, data: Data) -> FfiResult {
    return try!  FfiConverterTypeFfiResult.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_pty_write(
        FfiConverterString.lower(connectionId),
        FfiConverterData.lower(data),$0
    )
})
}
/**
 * Register an event callback. The callback receives `FfiEvent` messages
 * for PTY output, connection status changes, and transfer progress.
 * The callback is moved into a background Tokio task and forwarded to
 * the Swift layer. Must be called at least once before any event-producing
 * operations (PTY start, file transfer, etc.).
 */
public func rshellSetEventCallback(callback: FfiEventCallback) {try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_set_event_callback(
        FfiConverterCallbackInterfaceFfiEventCallback.lower(callback),$0
    )
}
}
/**
 * Cancel an in-flight transfer by its Swift-side UUID. Returns true
 * if a transfer was found and cancelled, false if the id wasn't
 * registered (already finished, never started, or unknown). The
 * running transfer's loop notices on its next chunk boundary and
 * returns `SftpError::Cancelled`.
 */
public func rshellSftpCancel(transferId: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_r_shell_macos_fn_func_rshell_sftp_cancel(
        FfiConverterString.lower(transferId),$0
    )
})
}
/**
 * Create a directory on the remote. Fails if the parent doesn't
 * exist or the name is already taken.
 */
public func rshellSftpCreateDir(connectionId: String, path: String)throws  {try rustCallWithError(FfiConverterTypeSftpError.lift) {
    uniffi_r_shell_macos_fn_func_rshell_sftp_create_dir(
        FfiConverterString.lower(connectionId),
        FfiConverterString.lower(path),$0
    )
}
}
/**
 * Delete an empty directory. Recursive removal is the UI's
 * responsibility — list_dir + per-entry delete in a loop with progress.
 */
public func rshellSftpDeleteDir(connectionId: String, path: String)throws  {try rustCallWithError(FfiConverterTypeSftpError.lift) {
    uniffi_r_shell_macos_fn_func_rshell_sftp_delete_dir(
        FfiConverterString.lower(connectionId),
        FfiConverterString.lower(path),$0
    )
}
}
/**
 * Delete a regular file. For directories, use `rshell_sftp_delete_dir`.
 */
public func rshellSftpDeleteFile(connectionId: String, path: String)throws  {try rustCallWithError(FfiConverterTypeSftpError.lift) {
    uniffi_r_shell_macos_fn_func_rshell_sftp_delete_file(
        FfiConverterString.lower(connectionId),
        FfiConverterString.lower(path),$0
    )
}
}
/**
 * Stream a remote file to a local path. Returns the byte count on
 * success. Publishes `TransferProgress` events on every SFTP chunk so
 * the UI can drive a progress bar — the consumer (Swift
 * `TransferQueueStore`) matches events back to the in-flight transfer
 * by `path`. `expected_size` lets the consumer compute a percentage;
 * pass `0` if unknown.
 *
 * `transfer_id` is the caller's stable handle (Swift uses the
 * per-transfer UUID). It's registered in a cancellation registry on
 * entry and removed on exit; `rshell_sftp_cancel(transfer_id)` walks
 * the registry to flip the token, and the chunk loop notices on the
 * next iteration.
 */
public func rshellSftpDownload(transferId: String, connectionId: String, remotePath: String, localPath: String, expectedSize: UInt64)throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSftpError.lift) {
    uniffi_r_shell_macos_fn_func_rshell_sftp_download(
        FfiConverterString.lower(transferId),
        FfiConverterString.lower(connectionId),
        FfiConverterString.lower(remotePath),
        FfiConverterString.lower(localPath),
        FfiConverterUInt64.lower(expectedSize),$0
    )
})
}
public func rshellSftpListDir(connectionId: String, path: String)throws  -> [FfiFileEntry] {
    return try  FfiConverterSequenceTypeFfiFileEntry.lift(try rustCallWithError(FfiConverterTypeSftpError.lift) {
    uniffi_r_shell_macos_fn_func_rshell_sftp_list_dir(
        FfiConverterString.lower(connectionId),
        FfiConverterString.lower(path),$0
    )
})
}
/**
 * Rename or move a file or directory.
 */
public func rshellSftpRename(connectionId: String, oldPath: String, newPath: String)throws  {try rustCallWithError(FfiConverterTypeSftpError.lift) {
    uniffi_r_shell_macos_fn_func_rshell_sftp_rename(
        FfiConverterString.lower(connectionId),
        FfiConverterString.lower(oldPath),
        FfiConverterString.lower(newPath),$0
    )
}
}
/**
 * Stream a local file to a remote path. See `rshell_sftp_download` for
 * the progress-event contract and the cancellation registry. The
 * local file is `stat`'d once before the transfer so progress events
 * carry a meaningful total.
 */
public func rshellSftpUpload(transferId: String, connectionId: String, localPath: String, remotePath: String)throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSftpError.lift) {
    uniffi_r_shell_macos_fn_func_rshell_sftp_upload(
        FfiConverterString.lower(transferId),
        FfiConverterString.lower(connectionId),
        FfiConverterString.lower(localPath),
        FfiConverterString.lower(remotePath),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_r_shell_macos_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_connect() != 1800) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_disconnect() != 30319) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_execute_command() != 15070) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_forget_host_key() != 53327) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_init() != 11104) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_keychain_delete() != 1661) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_keychain_is_supported() != 14889) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_keychain_list() != 36880) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_keychain_load() != 10085) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_keychain_save() != 41585) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_pty_close() != 28757) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_pty_resize() != 44514) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_pty_start() != 13587) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_pty_write() != 3580) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_set_event_callback() != 25155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_sftp_cancel() != 33240) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_sftp_create_dir() != 42046) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_sftp_delete_dir() != 56750) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_sftp_delete_file() != 46597) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_sftp_download() != 8155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_sftp_list_dir() != 57015) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_sftp_rename() != 3589) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_func_rshell_sftp_upload() != 1763) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_r_shell_macos_checksum_method_ffieventcallback_on_event() != 59523) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitFfiEventCallback()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all